### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by khalidchoukhmane**
Add Laravel icon to PHP table

### CODE REVIEW

**Comment by marwin1991** [comment]
@khalidchoukhmane thank you for contribution but can you look at 

https://github.com/marwin1991/profile-technology-icons#-contribution

we need png 400x400 :)

**Comment by khalidchoukhmane** [comment]
Ok 400x400.

**Comment by khalidchoukhmane** [comment]
I have added new [png and 400x400] Laravel and Symfony logo.

**Comment by marwin1991** [comment]
@khalidchoukhmane 

Hello, sorry for delay.

I will add it by my own, becasue I prefer host it on github istead external service

**Pull request closed without merging**
