### PR TITLE
Icons as Table

### PR DESCRIPTION
**Pull request by AnshumanMahato**
# Resolution for #5 Icons as Table

This PR adds the functionality for formatting icons in a table. 

## Screenshot
image
 
## PR Description

- Maximum number of columns is 8. Another row is added in case more than eight skills are selected.
- Maximum allowed size of icons if fixed to 50px if table mode is selected. Larger images tend to squish.
- Refactored generate function for simplification.

### CODE REVIEW

**Comment by AnshumanMahato** [comment]
live site : https://anshumanmahato.github.io/profile-technology-icons/

**Comment by marwin1991** [comment]
@AnshumanMahato thank you some much for contribiution!

I have one small idea: Can we make this as "unchecked" as default ? OR do you think checked is better?

**Comment by AnshumanMahato** [comment]
We can do that... As everything was checked by default so I kept it that way to be consistent.

**Comment by marwin1991** [comment]
> So, should I set it to unchecked?

@AnshumanMahato Yes :)

**Review by marwin1991 — APPROVED** [review]

**Pull request merged**
