### PR TITLE
Addition of Icon of MQTT technologies

### PR DESCRIPTION
**Pull request by Ramonmelod**
addition of five icons referent to MQTT technologies

### CODE REVIEW

**Comment by marwin1991** [comment]
@Ramonmelod Thank you so much for your contribution!

Can you provide 400 x 400 px icons? if you don't have time I can edit them in spare time :)

**Comment by Ramonmelod** [comment]
hello, @marwin1991. 
I'm sorry about the icon problem, I think the problem is just the first icon, as it is made with multiple parts I thought it was bigger than 400 X 400 px. To address this issue, I implemented two solutions:

Main Branch: I added an MQTT icon image in the path: src/assets/images  to the main branch and utilized it as the reference icon. 

Option2 Branch: Alternatively, in the "option2" branch, I utilized the following link as a reference icon: https://mqtt.org/assets/img/mqtt-logo-ver.jpg. But, I didn't like this  image due to its lack of transparency.

I did it in two forms because I don'1 know if my solution adding an image to the project is something that should be done. 

Please tell me what is the branch is more apropriated to this project. After you choose a branch shell I open a new pull request or is there any way to use this same pull request?
 thank you very much.

**Comment by marwin1991** [comment]
@Ramonmelod Hello, here you have
MQTT_400_400


:)

**Comment by Ramonmelod** [comment]
@marwin1991, thank you for the explanation. In the beginning I didn't get what you meant by drag and drop the image direct on the web editor, but now I did it. I changed all the icons to be exactly 400 x 400 px.

**Pull request merged**
